//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serverbooking.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class InfoServer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoServer()
        {
            this.BookingInfo = new HashSet<BookingInfo>();
        }
    
        public int ServerID { get; set; }
        public string Status { get; set; }
        public string ServerName { get; set; }
        public string Environment { get; set; }
        public Nullable<int> ActiveBookingID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingInfo> BookingInfo { get; set; }

        internal static void Add(HttpServerUtilityBase server)
        {
            throw new NotImplementedException();
        }
    }
}
